### ISSUE TITLE
サブモジュールの参照先を変更する

### ISSUE THREAD

**Issue by yoshimuraYuu** [WORD-COINS/article-template#2]
`article-template`のサブモジュールが差してる先が、プルリク用ブランチになっているので、 `texfiles`の`master`の先頭（ texfiles@54dcca2 ）に変更する。

**Comment by Nymphium** [comment]
masterにアプデートしました｡

https://github.com/WORD-COINS/article-template/commit/2058c127f45729060a8ff1fc400a36d1dc978738
