### ISSUE TITLE
JenkinsのLuaLaTeXでの動作

### ISSUE THREAD

**Issue by hidaruma** [WORD-COINS/article-template#48]
LuaLaTeX限定パッケージ使った場合、デフォルトではJenkinsのbuild.shがうまく動作しないように見えます。

ユーザーがプッシュする際にlatexmkrcのpdfmodeを書き換えるようにさせるか、‘ｔｏｕｃｈ　ｌｕａｔｅｘ‘など、なんらかの
LuaTeX使うぞアピールとそれを検知する部分が必要かもしれません（その場合`if`で分岐して`LATEXMK=pdflatex make`を使わせうようにするなど）。

**Comment by y-yu** [comment]
これはちょっと前から認識していたけど、そのとおりで、`Makefile`に`-pdf`オプションを追加してもらうようにREADMEに書くしかない。

**Comment by y-yu** [comment]
#53 で修理されたので閉じます。
