### ISSUE TITLE
slack通知を直す

### ISSUE THREAD

**Issue by Totsugekitai** [WORD-COINS/article-template#56]
現在bitbucket用になっているので直す。

**Comment by sksat** [comment]
これ #latex_feed に流すようにしたけどどう？(そういう話ではない？)

**Comment by Totsugekitai** [comment]
あ、言葉足らずだった。
CIの結果を通知したいということ。

**Comment by sksat** [comment]
あーそういうことか．そして`integrations/slack`くんはそれはできないんだなあ(PRのやつは出るから実用上そんなに困らなくはあるのだけど)

**Comment by sksat** [comment]
しかしこれは全commitに対して出てほしいやつなんだよなー

**Comment by sksat** [comment]
Actionsで`on: push`で`if: success`でwebhook発射しかないかなあ

**Comment by sksat** [comment]
各号リポジトリ毎にsecret差し込み必須だけど，それしかないかー

**Comment by sksat** [comment]
あーいやこれはwebhook吸い上げ太郎を生やしてやれば統一できるな？eventとしては飛ばせるんだから(思い出される某社で作ったブツ)

**Comment by Totsugekitai** [comment]
これは #68 とか #62 とかで終わったんかな？ @private-yusuke

**Comment by private-yusuke** [comment]
👀 そうですね、それらで完了しているため close します！
お知らせしていただいてありがとうございます 🙏
