### ISSUE TITLE
Haranoaji化したい

### ISSUE THREAD

**Issue by Totsugekitai** [WORD-COINS/article-template#57]
https://github.com/WORD-COINS/latex-build/issues/5#issue-1180293833 と連動してやりたくね？

**Comment by Totsugekitai** [comment]
@Azumabashi こっちお願いして良いですか？
Dockerイメージの方の修正は自分がやるので。

**Comment by Azumabashi** [comment]
プロチャレわかんなすぎて一周回って気持ち出てきたので見てみます

**Comment by Azumabashi** [comment]
確か LaTeX のデフォルト和文は既に harnoaji のはずなので，適当にやればよさそう
