### ISSUE TITLE
jisb5.ps とは何？

### ISSUE THREAD

**Issue by Azumabashi** [WORD-COINS/article-template#69]
jisb5.ps とは何？いる？

**Comment by Totsugekitai** [comment]
@Nymphium がコミットしているからそこから聞いた方が早そう。

**Comment by Azumabashi** [comment]
`ps2pdf` で変換したところ白紙が出てきたので，何か意味のあるファイルとも思えず．
`grep -rl jisb5` としてもヒットしないので使われていないと判断します．
不要なファイルを置いていても仕方がないので，削除の PR を出します．

**Comment by hidaruma** [comment]
pLaTeXでdvipdfmxまわりでJIS B5使おうとするときに必要になったりするやつだったと思う
